- params:
    git:
      repoName: it-test
      branches:
        - main
  scans:
    - type: secrets
      exclude_patterns:
        - "**/*.git*/**"
        - "**/*node_modules*/**"
        - "**/*target*/**"
        - "**/*venv*/**"
        - "**/dist/**"
